# Wordpress restore vars

# 作業用ディレクトリ
restore_work_dir: /tmp/wordpress-backup

#----------------------------------------
# 適宜変更する
#----------------------------------------
# WordPress バックアップ SQL データファイル名
sql_dump_file: wordpress.sql

# WordPress がインストールされているパス
wp_installed_path: /var/www/html/wordpress

# リストアされる WordPress の URL
wp_new_url: http://example.com/wp-new

# バックアップデータを作成した WordPress の URL
wp_old_url: http://example.com/wp-old

# バックアップデータが置かれているGitリポジトリ
wp_git_repo: https://github.com/example/git.git
#----------------------------------------
